In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
DS = pd.read_csv("placement.csv")

In [4]:
DS.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p      status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80      Placed  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28      Placed  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80      Placed  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43  Not Placed       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50      Placed  425000.0

In [5]:
DS.isnull().any()

sl_no             False
gender            False
ssc_p             False
ssc_b             False
hsc_p             False
hsc_b             False
hsc_s             False
degree_p          False
degree_t          False
workex            False
etest_p           False
specialisation    False
mba_p             False
status            False
salary             True
dtype: bool

In [6]:
DS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
sl_no             215 non-null int64
gender            215 non-null object
ssc_p             215 non-null float64
ssc_b             215 non-null object
hsc_p             215 non-null float64
hsc_b             215 non-null object
hsc_s             215 non-null object
degree_p          215 non-null float64
degree_t          215 non-null object
workex            215 non-null object
etest_p           215 non-null float64
specialisation    215 non-null object
mba_p             215 non-null float64
status            215 non-null object
salary            148 non-null float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB


# ONE HOT ENCODING

### 1 3 5 6 8 9 11


In [7]:
DS["ssc_b"].unique()

array(['Others', 'Central'], dtype=object)

In [8]:
DS["hsc_s"].unique()

array(['Commerce', 'Science', 'Arts'], dtype=object)

In [9]:
DS["degree_t"].unique()

array(['Sci&Tech', 'Comm&Mgmt', 'Others'], dtype=object)

In [10]:
DS["specialisation"].unique()

array(['Mkt&HR', 'Mkt&Fin'], dtype=object)

In [11]:
DS.shape

(215, 15)

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
DS["status"] = le.fit_transform(DS["status"])

In [13]:
x = DS.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12]]

In [14]:
x

gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p   degree_t  \
0        M  67.00   Others  91.00   Others  Commerce     58.00   Sci&Tech   
1        M  79.33  Central  78.33   Others   Science     77.48   Sci&Tech   
2        M  65.00  Central  68.00  Central      Arts     64.00  Comm&Mgmt   
3        M  56.00  Central  52.00  Central   Science     52.00   Sci&Tech   
4        M  85.80  Central  73.60  Central  Commerce     73.30  Comm&Mgmt   
5        M  55.00   Others  49.80   Others   Science     67.25   Sci&Tech   
6        F  46.00   Others  49.20   Others  Commerce     79.00  Comm&Mgmt   
7        M  82.00  Central  64.00  Central   Science     66.00   Sci&Tech   
8        M  73.00  Central  79.00  Central  Commerce     72.00  Comm&Mgmt   
9        M  58.00  Central  70.00  Central  Commerce     61.00  Comm&Mgmt   
10       M  58.00  Central  61.00  Central  Commerce     60.00  Comm&Mgmt   
11       M  69.60  Central  68.40  Central  Commerce     78.30  Comm&Mgmt   
12       F  47.00  Central  55.00   Others   Science     65.00  Comm&Mgmt   
13       F  77.00  Central  87.00  Central  Commerce     59.00  Comm&Mgmt   
14       M  62.00  Central  47.00  Central  Commerce     50.00  Comm&Mgmt   
15       F  65.00  Central  75.00  Central  Commerce     69.00  Comm&Mgmt   
16       M  63.00  Central  66.20  Central  Commerce     65.60  Comm&Mgmt   
17       F  55.00  Central  67.00  Central  Commerce     64.00  Comm&Mgmt   
18       F  63.00  Central  66.00  Central  Commerce     64.00  Comm&Mgmt   
19       M  60.00   Others  67.00   Others      Arts     70.00  Comm&Mgmt   
20       M  62.00   Others  65.00   Others  Commerce     66.00  Comm&Mgmt   
21       F  79.00   Others  76.00   Others  Commerce     85.00  Comm&Mgmt   
22       F  69.80   Others  60.80   Others   Science     72.23   Sci&Tech   
23       F  77.40   Others  60.00   Others   Science     64.74   Sci&Tech   
24       M  76.50   Others  97.70   Others   Science     78.86   Sci&Tech   
25       F  52.58   Others  54.60  Central  Commerce     50.20  Comm&Mgmt   
26       M  71.00   Others  79.00   Others  Commerce     66.00  Comm&Mgmt   
27       M  63.00   Others  67.00   Others  Commerce     66.00  Comm&Mgmt   
28       M  76.76   Others  76.50   Others  Commerce     67.50  Comm&Mgmt   
29       M  62.00  Central  67.00  Central  Commerce     58.00  Comm&Mgmt   
..     ...    ...      ...    ...      ...       ...       ...        ...   
185      F  88.00  Central  72.00  Central   Science     78.00     Others   
186      F  52.00  Central  64.00  Central  Commerce     61.00  Comm&Mgmt   
187      M  78.50  Central  65.50  Central   Science     67.00   Sci&Tech   
188      M  61.80   Others  47.00   Others  Commerce     54.38  Comm&Mgmt   
189      F  54.00  Central  77.60   Others  Commerce     69.20  Comm&Mgmt   
190      F  64.00   Others  70.20  Central  Commerce     61.00  Comm&Mgmt   
191      M  67.00   Others  61.00  Central   Science     72.00  Comm&Mgmt   
192      M  65.20  Central  61.40  Central  Commerce     64.80  Comm&Mgmt   
193      F  60.00  Central  63.00  Central      Arts     56.00     Others   
194      M  52.00   Others  55.00   Others  Commerce     56.30  Comm&Mgmt   
195      M  66.00  Central  76.00  Central  Commerce     72.00  Comm&Mgmt   
196      M  72.00   Others  63.00   Others   Science     77.50   Sci&Tech   
197      F  83.96   Others  53.00   Others   Science     91.00   Sci&Tech   
198      F  67.00  Central  70.00  Central  Commerce     65.00     Others   
199      M  69.00   Others  65.00   Others  Commerce     57.00  Comm&Mgmt   
200      M  69.00   Others  60.00   Others  Commerce     65.00  Comm&Mgmt   
201      M  54.20  Central  63.00   Others   Science     58.00  Comm&Mgmt   
202      M  70.00  Central  63.00  Central   Science     66.00   Sci&Tech   
203      M  55.68   Others  61.33   Others  Commerce     56.87  Comm&Mgmt   
204      F  74.00   Others  73.00   Others  Commerce     73.00  Comm&Mgmt   


In [15]:
x.shape

(215, 12)

In [16]:
y = DS.iloc[:,13].values
y

array([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [17]:
DS.head()

sl_no gender  ssc_p    ssc_b  hsc_p    hsc_b     hsc_s  degree_p  \
0      1      M  67.00   Others  91.00   Others  Commerce     58.00   
1      2      M  79.33  Central  78.33   Others   Science     77.48   
2      3      M  65.00  Central  68.00  Central      Arts     64.00   
3      4      M  56.00  Central  52.00  Central   Science     52.00   
4      5      M  85.80  Central  73.60  Central  Commerce     73.30   

    degree_t workex  etest_p specialisation  mba_p  status    salary  
0   Sci&Tech     No     55.0         Mkt&HR  58.80       1  270000.0  
1   Sci&Tech    Yes     86.5        Mkt&Fin  66.28       1  200000.0  
2  Comm&Mgmt     No     75.0        Mkt&Fin  57.80       1  250000.0  
3   Sci&Tech     No     66.0         Mkt&HR  59.43       0       NaN  
4  Comm&Mgmt     No     96.8        Mkt&Fin  55.50       1  425000.0

In [18]:
x.shape

(215, 12)

In [19]:
DS.iloc[:,[1,3,5,6,8,9,11]]

gender    ssc_b    hsc_b     hsc_s   degree_t workex specialisation
0        M   Others   Others  Commerce   Sci&Tech     No         Mkt&HR
1        M  Central   Others   Science   Sci&Tech    Yes        Mkt&Fin
2        M  Central  Central      Arts  Comm&Mgmt     No        Mkt&Fin
3        M  Central  Central   Science   Sci&Tech     No         Mkt&HR
4        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
5        M   Others   Others   Science   Sci&Tech    Yes        Mkt&Fin
6        F   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
7        M  Central  Central   Science   Sci&Tech    Yes        Mkt&Fin
8        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
9        M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
10       M  Central  Central  Commerce  Comm&Mgmt    Yes         Mkt&HR
11       M  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin
12       F  Central   Others   Science  Comm&Mgmt     No         Mkt&HR
13       F  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
14       M  Central  Central  Commerce  Comm&Mgmt     No         Mkt&HR
15       F  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin
16       M  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin
17       F  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
18       F  Central  Central  Commerce  Comm&Mgmt     No         Mkt&HR
19       M   Others   Others      Arts  Comm&Mgmt    Yes        Mkt&Fin
20       M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR
21       F   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
22       F   Others   Others   Science   Sci&Tech     No         Mkt&HR
23       F   Others   Others   Science   Sci&Tech    Yes        Mkt&Fin
24       M   Others   Others   Science   Sci&Tech     No        Mkt&Fin
25       F   Others  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin
26       M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin
27       M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR
28       M   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin
29       M  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
..     ...      ...      ...       ...        ...    ...            ...
185      F  Central  Central   Science     Others     No         Mkt&HR
186      F  Central  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
187      M  Central  Central   Science   Sci&Tech    Yes        Mkt&Fin
188      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
189      F  Central   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
190      F   Others  Central  Commerce  Comm&Mgmt     No        Mkt&Fin
191      M   Others  Central   Science  Comm&Mgmt     No        Mkt&Fin
192      M  Central  Central  Commerce  Comm&Mgmt    Yes        Mkt&Fin
193      F  Central  Central      Arts     Others    Yes         Mkt&HR
194      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
195      M  Central  Central  Commerce  Comm&Mgmt    Yes         Mkt&HR
196      M   Others   Others   Science   Sci&Tech    Yes        Mkt&Fin
197      F   Others   Others   Science   Sci&Tech     No         Mkt&HR
198      F  Central  Central  Commerce     Others     No         Mkt&HR
199      M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR
200      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
201      M  Central   Others   Science  Comm&Mgmt     No         Mkt&HR
202      M  Central  Central   Science   Sci&Tech     No         Mkt&HR
203      M   Others   Others  Commerce  Comm&Mgmt     No         Mkt&HR
204      F   Others   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin
205      M   Others   Others  Commerce  Comm&Mgmt     No        Mkt&Fin
206      M  Central  Central   Science  Comm&Mgmt     No        Mkt&Fin
207      M  Central   Others  Commerce  Comm&Mgmt    Yes        Mkt&Fin
208      F  Central   Others   Science  Comm

In [20]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[0,2,4,5,7,8,10])],remainder="passthrough")

In [21]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh",OneHotEncoder(),[0,2,4,5,7,8,10])],remainder="passthrough")
# ct = ColumnTransformer([("oh",OneHotEncoder(),[0,2,4,5,7,8,10])],remainder="passthrough")
x = ct.fit_transform(x)

In [22]:
x

array([[ 0.  ,  1.  ,  0.  , ..., 58.  , 55.  , 58.8 ],
       [ 0.  ,  1.  ,  1.  , ..., 77.48, 86.5 , 66.28],
       [ 0.  ,  1.  ,  1.  , ..., 64.  , 75.  , 57.8 ],
       ...,
       [ 0.  ,  1.  ,  0.  , ..., 73.  , 59.  , 69.72],
       [ 1.  ,  0.  ,  0.  , ..., 58.  , 70.  , 60.23],
       [ 0.  ,  1.  ,  1.  , ..., 53.  , 89.  , 60.22]])

In [23]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [24]:
x_test[0]

array([ 1.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,
        0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  , 67.  , 70.  ,
       65.  , 88.  , 71.96])

In [25]:
x.shape

(215, 21)

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
cat = Sequential()

In [29]:
cat.add(Dense(21,kernel_initializer = "random_uniform",activation ="relu"))

In [30]:
cat.add(Dense(42,kernel_initializer = "random_uniform",activation ="relu"))

In [31]:
cat.add(Dense(1,kernel_initializer = "random_uniform",activation ="sigmoid"))

In [32]:
cat.compile("adam","binary_crossentropy",metrics = ["accuracy"])

In [33]:
cat.fit(x_train,y_train,batch_size = 32, epochs=170)

Epoch 1/170
6/6 [==============================] - 1s 4ms/step - loss: 0.6917 - accuracy: 0.6919
Epoch 2/170
6/6 [==============================] - 0s 3ms/step - loss: 0.6880 - accuracy: 0.7035
Epoch 3/170
6/6 [==============================] - 0s 3ms/step - loss: 0.6824 - accuracy: 0.7035
Epoch 4/170
6/6 [==============================] - 0s 4ms/step - loss: 0.6743 - accuracy: 0.7035
Epoch 5/170
6/6 [==============================] - 0s 3ms/step - loss: 0.6614 - accuracy: 0.7035
Epoch 6/170
6/6 [==============================] - 0s 3ms/step - loss: 0.6444 - accuracy: 0.7035
Epoch 7/170
6/6 [==============================] - 0s 4ms/step - loss: 0.6192 - accuracy: 0.7035
Epoch 8/170
6/6 [==============================] - 0s 4ms/step - loss: 0.5888 - accuracy: 0.7035
Epoch 9/170
6/6 [==============================] - 0s 3ms/step - loss: 0.5511 - accuracy: 0.7151
Epoch 10/170
6/6 [==============================] - 0s 4ms/step - loss: 0.5139 - accuracy: 0.7558
Epoch 11/170
6/6 [===========

6/6 [==============================] - 0s 3ms/step - loss: 0.0783 - accuracy: 0.9651
Epoch 85/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0770 - accuracy: 0.9709
Epoch 86/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0764 - accuracy: 0.9651
Epoch 87/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0734 - accuracy: 0.9709
Epoch 88/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0731 - accuracy: 0.9709
Epoch 89/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0733 - accuracy: 0.9709
Epoch 90/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0708 - accuracy: 0.9709
Epoch 91/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0693 - accuracy: 0.9709
Epoch 92/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0679 - accuracy: 0.9709
Epoch 93/170
6/6 [==============================] - 0s 4ms/step - loss: 0.0673 - accuracy: 0.9709
Epoch 94/170
6/6 [===============

6/6 [==============================] - 0s 3ms/step - loss: 0.0240 - accuracy: 1.0000
Epoch 168/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0234 - accuracy: 0.9884
Epoch 169/170
6/6 [==============================] - 0s 3ms/step - loss: 0.0231 - accuracy: 0.9942
Epoch 170/170
6/6 [==============================] - 0s 4ms/step - loss: 0.0231 - accuracy: 0.9942


In [39]:
# TEST = cat.predict_classes(sc.transform(ct.transform([[M,69.60,Central,68.40,Central,Commerce,78.30,Comm&Mgmt,Yes,60,Mkt&Fin,63.7]])))
TEST = cat.predict_classes(sc.transform(ct.transform([['F',52.58,'Central',54.60,'Central','Commerce',50.20,'Comm&Mgmt','Yes',76,'Mkt&Fin',65.33]])))
# TEST =cat.predict_classes(sc.fit_transform([[1.  ,  0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  0.  ,
#         0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  , 67.  , 70.  ,
#        65.  , 88.  , 71.96]]))
# TEST = cat.predict_classes(x_test)
# test = ct.fit_transform([['M',69.60,'Central',68.40,'Central','Commerce',78.30,'Comm&Mgmt','Yes',60,'Mkt&Fin',63.7]])
# # TEST = cat.predict(sc.fit_transform(ct.fit_transform([['M',69.60,'Central',68.40,'Central','Commerce',78.30,'Comm&Mgmt','Yes',60,'Mkt&Fin',63.7]])[0]))
TEST

C:\Users\Kalyan\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[0]])

###### x_test


In [ ]:
test = TEST[:,0]
test

In [ ]:
y_test

In [ ]:
len(y_test)